"""Apply local patches to vendored dependencies."""

import argparse
from pathlib import Path


def patch_dlpm(vendor_root: Path) -> list[Path]:
    dlpm_root = vendor_root / "DLPM"
    config_dir = dlpm_root / "dlpm" / "configs"
    source_path = config_dir / "2d_data.yml"
    target_path = config_dir / "2d_sas.yml"

    if not dlpm_root.exists():
        return []
    if not source_path.exists():
        raise FileNotFoundError(f"Missing DLPM base config: {source_path}")

    text = source_path.read_text()
    text = text.replace(
        "  dataset: gmm_grid     # sas_grid\n",
        "  dataset: sas\n",
        1,
    )
    text = text.replace(
        "  n_mixture: 9          # must be square. set to None if not a grid mixture\n",
        "  n_mixture: null\n",
        1,
    )
    text = (
        "# Auto-generated by scripts/patch.vendor.py.\n"
        "# This config provides the isotropic alpha-stable DLPM setup.\n\n" + text
    )

    if target_path.exists() and target_path.read_text() == text:
        return []

    target_path.write_text(text)
    return [target_path]


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Apply GenDynamics patches to vendored dependencies.")
    parser.add_argument(
        "--vendor-root",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "gendynamics" / "_vendor",
        help="Root directory containing vendored repositories.",
    )
    args = parser.parse_args()

    vendor_root = args.vendor_root.expanduser().resolve()
    patched_paths = patch_dlpm(vendor_root)
    for path in patched_paths:
        print(f"patched {path}")
    if not patched_paths:
        print("no vendor patches applied")
